// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTestingSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void invalidUsernameorPassword() {
    driver.get("https://evening-anchorage-27251.herokuapp.com/login/login");
    driver.manage().window().setSize(new Dimension(1433, 801));
    driver.findElement(By.id("id_username")).sendKeys("Krishna");
    driver.findElement(By.id("id_password")).click();
    driver.findElement(By.id("id_password")).sendKeys("admin");
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("Invalid login! Please try again."));
    driver.findElement(By.id("id_username")).click();
    driver.findElement(By.id("id_username")).sendKeys("myProject");
    driver.findElement(By.id("id_password")).click();
    driver.findElement(By.id("id_password")).sendKeys("Krishna@123");
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("Invalid login! Please try again."));
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("id_username")).sendKeys("user1");
    driver.findElement(By.id("id_password")).click();
    driver.findElement(By.id("id_password")).sendKeys("user1");
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("Invalid login! Please try again."));
    driver.close();
  }
  @Test
  public void valideUsernamePassword() {
    driver.get("https://evening-anchorage-27251.herokuapp.com/login");
    driver.manage().window().setSize(new Dimension(1433, 801));
    driver.findElement(By.id("id_username")).sendKeys("krishna");
    driver.findElement(By.id("id_password")).click();
    driver.findElement(By.id("id_password")).sendKeys("Project@123");
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector("h3:nth-child(1)")).getText(), is("Bank Account"));
    driver.get("https://evening-anchorage-27251.herokuapp.com/login");
    driver.findElement(By.id("id_username")).sendKeys("User1");
    driver.findElement(By.id("id_password")).click();
    driver.findElement(By.id("id_password")).sendKeys("Project@123");
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector("h3:nth-child(1)")).getText(), is("Bank Account"));
    driver.close();
  }
}
