# Generated by Django 3.1.7 on 2021-03-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_auto_20210317_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='title',
        ),
    ]
