# Generated by Django 3.1.7 on 2021-03-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_deposit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='complete',
        ),
    ]
