# Generated by Django 3.1.7 on 2021-03-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_remove_deposit_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='amount',
            new_name='depositAmount',
        ),
    ]
